import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/scss/main.scss';
import '@/app/globals.css';
import Header from "@/app/ui/Header";
import Footer from "@/app/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className='max-w-[1920px] relative  mx-auto overflow-x-hidden'>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
